name: Eat
main: me.khuirulhuda.eat.Main
version: 1.1
website: https://khuirul-huda.github.io/Eat
description: Simple plugin for give free food to players instead of instant fill foodbar
author: Khuirul-Huda
load: POSTWORLD

commands:
    eat:
        description: Give many food for you
        usage: /eat
        