name: Eat
version: 0.2
main: me.khuirulhuda.eat.Main
author: Khuirul-Huda
load: POSTWORLD
website: https://khuirul-huda.github.io/Eat

commands:
    eat:
        description: Give many food for you
        usage: /eat
        